service: got-your-money-api

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 10

plugins:
  - serverless-offline

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: items
          method: post
          cors: true

  getOne:
    handler: handler.getOne
    events:
      - http:
          path: items/{id}
          method: get
          cors: true

  getAll:
    handler: handler.getAll
    events:
     - http:
         path: items
         method: get
         cors: true

  update:
    handler: handler.update
    events:
     - http:
         path: items/{id}
         method: put
         cors: true

  delete:
    handler: handler.delete
    events:
      - http:
          path: items/{id}
          method: delete
          cors: true
